name: First
on:
  push:
    branches:
      - main
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is first Github Actions"
  second:
    name: PWD & LS
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Print working directory
        run: pwd
      - uses: actions/checkout@v3
      - run: ls -al
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - if: steps.npm-cache.outputs.cache-hit == 'true'
        run: echo 'npm cache hit'
      - if: steps.npm-cache.outputs.cache-hit != 'true'
        run: echo 'npm cache hit'
      - run: npm ci
