name: First
on:
  push:
    branches:
      - main
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is first Github Actions"
  second:
    name: PWD & LS
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Print working directory
        run: pwd
      - uses: actions/checkout@v3
      - run: ls -al
